//
//  ItemData.swift
//  єОзброєння
//
//  Created by Oleksandr Smakhtin on 23.08.2022.
//

import Foundation


struct Item {
    
    let items = [
        
        ItemModel(item: "5,45-мм ПСМ", property: [Property(name: "Калібр, мм.", value: "5,45×18"),
                                                  Property(name: "Принцип дії", value: "вільний затвор"),
                                                  Property(name: "Вага без набоїв, г.", value: "460"),
                                                  Property(name: "Вага з набоями, г.", value: "500"),
                                                  Property(name: "Довжина, мм.", value: "155"),
                                                  Property(name: "Довжина ствола, мм.", value: "84,6"),
                                                  Property(name: "Ширина, мм.", value: "18"),
                                                  Property(name: "Висота, мм.", value: "106"),
                                                  Property(name: "Початкова швидкість кулі, м/с", value: "315"),
                                                  Property(name:
                                                            "Швидкострільність, пострілів/хв", value: "30"),
                                                  Property(name: "Прицільна дальність, м", value: "25"),
                                                  Property(name: "Місткість магазину, патронів", value: "8"),
                                                  Property(name: "Нарізи, шт", value: "6")]),
        
        ItemModel(item: "5,7-мм пістолет «Форт-28»", property: [Property(name: "Калібр, мм.", value: "5,7х28"),
                                                  Property(name: "Принцип дії", value: "напіввільний затвор"),
                                                  Property(name: "Ударно-спусковий механізм", value: "подвійний"),
                                                  Property(name: "Загальна довжина, мм.", value: "202"),
                                                  Property(name: "Висота, мм.", value: "135"),
                                                  Property(name: "Ширина, мм.", value: "33"),
                                                  Property(name: "Довжина ствола, мм.", value: "115,5"),
                                                  Property(name: "Вага без набоїв г.", value: "700"),
                                                  Property(name: "Місткість магазину, патронів", value: "20"),
                                                  Property(name:"Зусилля спуску, кгс.", value: "1,5-3,5"),
                                                  Property(name: "Початкова швидкість кулі, м/с", value: "600"),
                                                  Property(name: "Місткість магазину, набоїв", value: "20")]),
        
        ItemModel(item: "7,62-мм пістолет ТТ", property: [Property(name: "Калібр, мм.", value: "7,62×25"),
                                                  Property(name: "Вага без набоїв, г.", value: "854"),
                                                  Property(name: "Вага з набоями, г.", value: "940"),
                                                  Property(name: "Довжина, мм.", value: "195"),
                                                  Property(name: "Довжина ствола, мм.", value: "116"),
                                                  Property(name: "Висота, мм.", value: "130"),
                                                  Property(name: "Ширина, мм.", value: "30"),
                                                  Property(name: "Початкова швидкість кулі, м/с", value: "420"),
                                                  Property(name: "Швидкострільність, пострілів/хв", value: "48"),
                                                  Property(name:"Прицільна дальність, м.", value: "50"),
                                                  Property(name: "Місткість магазину, патронів", value: "8"),
                                                  Property(name: "Нарізи, шт.", value: "4")]),
        
        ItemModel(item: "9-мм пістолет Макарова (ПМ)", property: [Property(name: "Калібр, мм.", value: "9х18"),
                                                  Property(name: "Принцип дії", value: "вільний затвор"),
                                                  Property(name: "Вага без набоїв, г.", value: "733"),
                                                  Property(name: "Вага з набоями, г.", value: "810"),
                                                  Property(name: "Довжина, мм.", value: "161,5"),
                                                  Property(name: "Довжина ствола, мм.", value: "93,5"),
                                                  Property(name: "Ширина, мм.", value: "29,4"),
                                                  Property(name: "Початкова швидкість кулі, м/с", value: "315"),
                                                  Property(name: "Швидкострільність, пострілів/хв", value: "30"),
                                                  Property(name:"Прицільна дальність, м.", value: "50"),
                                                  Property(name: "Місткість магазину, патронів", value: "8"),
                                                  Property(name: "Нарізи, шт.", value: "4")]),
        
        ItemModel(item: "9-мм пістолет «Форт-12»", property: [Property(name: "Калібр, мм.", value: "9х18"),
                                                  Property(name: "Принцип дії", value: "вільний затвор"),
                                                  Property(name: "Cпусковий механізм", value: "один. та подв."),
                                                  Property(name: "Загальна довжина, мм.", value: "180"),
                                                  Property(name: "Висота, мм.", value: "131"),
                                                  Property(name: "Ширина, мм.", value: "33"),
                                                  Property(name: "Довжина ствола, мм.", value: "95"),
                                                  Property(name: "Вага без набоїв, г.", value: "830"),
                                                  Property(name: "Місткість магазину, патронів", value: "15"),
                                                  Property(name:"Початкова швидкість кулі, м/с", value: "320"),
                                                  Property(name: "Швидкострільність, пострілів/хв", value: "40"),
                                                  Property(name: "Прицільна дальність, м.", value: "25"),
                                                  Property(name: "Нарізи", value: "6")]),
        
        ItemModel(item: "9-мм пістолет «Форт-14ТП»", property: [Property(name: "Калібр, мм.", value: "9х18"),
                                                  Property(name: "Принцип дії", value: "вільний затвор"),
                                                  Property(name: "Cпусковий механізм", value: "один. та подв."),
                                                  Property(name: "Загальна довжина, мм.", value: "210"),
                                                  Property(name: "Висота, мм.", value: "140"),
                                                  Property(name: "Ширина, мм.", value: "33"),
                                                  Property(name: "Довжина ствола, мм.", value: "123,5"),
                                                  Property(name: "Вага без набоїв, г.", value: "920"),
                                                  Property(name: "Місткість магазину, патронів", value: "16/24"),
                                                  Property(name:"Початкова швидкість кулі, м/с", value: "335"),
                                                  Property(name: "Швидкострільність, пострілів/хв", value: "50"),
                                                  Property(name: "Прицільна дальність, м.", value: "25"),
                                                  Property(name: "Нарізи", value: "6"),
                                                  Property(name: "Сумісність", value: "Глушник ПЗРЗП-029"),
                                                  Property(name: "Довжина, мм.", value: "193"),
                                                  Property(name: "Діаметр, мм.", value: "38"),
                                                  Property(name: "Вага, г.", value: "370"),
                                                  Property(name: "Зниження рівня звуку дБ.", value: "25")]),
        
        ItemModel(item: "9-мм пістолет «Форт-14ПП»", property: [Property(name: "Калібр, мм.", value: "9х19"),
                                                  Property(name: "Принцип дії", value: "короткий хід"),
                                                  Property(name: "Cпусковий механізм", value: "один. та подв."),
                                                  Property(name: "Загальна довжина, мм.", value: "218"),
                                                  Property(name: "Висота, мм.", value: "140"),
                                                  Property(name: "Ширина, мм.", value: "35"),
                                                  Property(name: "Довжина ствола, мм.", value: "116"),
                                                  Property(name: "Вага без набоїв, г.", value: "950"),
                                                  Property(name: "Місткість магазину, патронів", value: "16"),
                                                  Property(name:"Початкова швидкість кулі, м/с", value: "320"),
                                                  Property(name: "Швидкострільність, пострілів/хв", value: "50"),
                                                  Property(name: "Прицільна дальність, м.", value: "25"),
                                                  Property(name: "Нарізи", value: "6")]),
        
        ItemModel(item: "9-мм пістолет «Форт-17»", property: [Property(name: "Калібр, мм.", value: "9х18"),
                                                  Property(name: "Принцип дії", value: "вільний затвор"),
                                                  Property(name: "Cпусковий механізм", value: "один. та подв."),
                                                  Property(name: "Загальна довжина, мм.", value: "179"),
                                                  Property(name: "Висота, мм.", value: "131"),
                                                  Property(name: "Ширина, мм.", value: "35"),
                                                  Property(name: "Довжина ствола, мм.", value: "97"),
                                                  Property(name: "Вага без набоїв, г.", value: "680"),
                                                  Property(name: "Місткість магазину, патронів", value: "15"),
                                                  Property(name:"Початкова швидкість кулі, м/с", value: "320"),
                                                  Property(name: "Швидкострільність, пострілів/хв", value: "40"),
                                                  Property(name: "Прицільна дальність, м.", value: "25"),
                                                  Property(name: "Нарізи", value: "6")]),
        
        ItemModel(item: "Помпова рушниця «Форт-500»", property: [Property(name: "Модифікації", value: "АС/МС/М1С/ТС"),
                                                  Property(name: "Калібр", value: "12/76-мм"),
                                                  Property(name: "Принцип дії", value: "ручна перезарядка"),
                                                  Property(name: "Довж. з прикладом, см.", value: "101/87/84/104"),
                                                  Property(name: "Довж. без прикладу, см.", value: "75/78/58/94"),
                                                  Property(name: "Довж. ствола, см.", value: "51/34/34/51"),
                                                  Property(name: "Вага без набоїв, кг.", value: "14,1/4,1/4,3/4,0"),
                                                  Property(name: "Місткість магазину", value: "5/4/4/6")]),
        
        ItemModel(item: "7,62-мм самозарядний карабін Симонова (СКС)", property: [Property(name: "Калібр, мм.", value: "7,62×39"),
                                                  Property(name: "Вага з набоями, кг.", value: "3,9"),
                                                  Property(name: "Вага без набоїв, кг.", value: "3,75"),
                                                  Property(name: "Довжина, мм.", value: "1020"),
                                                  Property(name: "Початкова швидкість кулі, м/с", value: "735"),
                                                  Property(name: "Швидкострільність, пострілів/хв", value: "40"),
                                                  Property(name: "Прицільна дальність, м.", value: "1000"),
                                                  Property(name: "Ефективна дальність, м.", value: "400"),
                                                  Property(name: "Макс. дальність м.", value: "1500"),
                                                  Property(name:"Місткість магазину, патронів", value: "10"),
                                                  Property(name: "Нарізи", value: "4")]),
        
        ItemModel(item: "9-мм пістолет-кулемет «Форт-224»", property: [Property(name: "Калібр, мм.", value: "9х19"),
                                                  Property(name: "Загальна довжина, мм.", value: "580"),
                                                  Property(name: "Довжина ствола, мм.", value: "330"),
                                                  Property(name: "Вага без набоїв, кг.", value: "3,6"),
                                                  Property(name: "Місткість магазину, патронів", value: "32"),
                                                  Property(name: "Початкова швидкість кулі, м/с", value: "420"),
                                                  Property(name: "Прицільна дальність, м.", value: "200"),
                                                  Property(name: "Темп стрільби (постр./хв.)", value: "800"),
                                                  Property(name: "Нарізи", value: "6")]),
        
        ItemModel(item: "9-мм пістолет-кулемет «Форт-226»", property: [Property(name: "Калібр, мм.", value: "9х19"),
                                                  Property(name: "Принцип дії", value: "вільний затвор"),
                                                  Property(name: "Довжина з прикладом мм.", value: "529"),
                                                  Property(name: "Довжина без прикладу", value: "300"),
                                                  Property(name: "Довжина ствола, мм.", value: "152"),
                                                  Property(name: "Вага без набоїв, кг.", value: "2,2"),
                                                  Property(name: "Місткість магазину, патронів", value: "32"),
                                                  Property(name: "Початкова швидкість кулі, м/с", value: "420"),
                                                  Property(name: "Прицільна дальність, м.", value: "200"),
                                                  Property(name:"Темп стрільби (постр./хв.)", value: "1200"),
                                                  Property(name: "Нарізи", value: "4")]),
        
        ItemModel(item: "9-мм пістолет-кулемет «Форт-230»", property: [Property(name: "Калібр, мм.", value: "9х19"),
                                                  Property(name: "Принцип дії", value: "вільний затвор"),
                                                  Property(name: "Режим вогню", value: "один./автомат."),
                                                  Property(name: "Довжина з прикладом мм.", value: "400"),
                                                  Property(name: "Довжина без прикладу", value: "600"),
                                                  Property(name: "Довжина ствола, мм.", value: "160"),
                                                  Property(name: "Вага без набоїв, кг.", value: "2,5"),
                                                  Property(name: "Прицільна дальність, м.", value: "200"),
                                                  Property(name: "Темп стрільби (постр./хв.)", value: "800"),
                                                  Property(name:"Місткість магазину, патронів", value: "20/30"),
                                                  Property(name: "Нарізи", value: "6")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),
        
        ItemModel(item: "", property: [Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name:"", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: ""),
                                                  Property(name: "", value: "")]),

        
        
        
    ]
    
}
